### PR TITLE
Add crash test

### PR DESCRIPTION
**Pull request by vkatsuba**
Added crash test for fix https://github.com/bmizhen/rec-avro/pull/3
The test JSON was get from AVRO use `reader/1` of `fastavro` library

### CODE REVIEW

**Comment by bmizhen** [comment]
x = load_json('tests/test_data2.json')
    assert from_rec_avro_destructive(x) == x

Can't do that, from_rec_avro_destructive(x) potentially destoys x.

I am not sure from your test data what is the nature of the bug. Can you
make a minimal test case that exhibits the problem?
Also, make it a literal data structure in python file plz.

**Comment by vkatsuba** [comment]
> We need to fail lound, not silently, I can see adding a descriptive message, but throwing the same exception.

What if add condition if `o` is `dict` and has `"_"` key and if not, return `rec_object` with printing `Warning` ans skip exception for this case?

**Comment by bmizhen** [comment]
Don't think it's a good idea. I want to fail fast and loud:

https://dzone.com/articles/fail-fast-principle-in-software-development

Can you give me more context on your use case? Why would
you want to call decode on something that was not encoded?

**Comment by vkatsuba** [comment]
Hi @bmizhen,

The my case is - I have a `*.avro` or `*.lif` files with some data and I just try to parse recursively it with load records from avro for generate JSON schema

Regards,
@vkatsuba

**Comment by bmizhen** [comment]
Would this help?

https://github.com/bmizhen/rec-avro/blob/bf170d5413619d3bbcff768667f90094fe5b962c/src/rec_avro/core.py#L150

**Comment by bmizhen** [comment]
This should be done on the schema from the avro file.

**Comment by vkatsuba** [comment]
I see, you mean need to detect if object has `__rec_avro_schema__` if yes - we can try to use `from_rec_avro_destructive/1`

**Comment by bmizhen** [comment]
Not the data object, but the schema object from the avro file.

**Comment by vkatsuba** [comment]
Thanks. I will check few points and if your solution is helped me, I will close this PR. Many thanks for your time.

Best Regards,
--V

**Comment by vkatsuba** [comment]
Approach what was provided by @bmizhen is helped. PR is closed.
@bmizhen many thanks for your time.
Regards,
--V

**Pull request closed without merging**
